name: Leap Deploy Validate
description: |
  Validates leap-deploy.yaml or folded configuration against the predefined schema to ensure correctness.

inputs:
  file-path:
    description: Path to the configuration file
    required: true
  version:
    description: Schema version to validate against
    required: false
    default: "v0"
  schema-type:
    description: "Schema type: 'input' for leap-deploy.yaml, 'folded' for folded configs"
    required: false
    default: "input"

runs:
  using: composite
  steps:
    - name: Determine schema file
      id: schema
      shell: bash
      run: |
        if [ "${{ inputs.schema-type }}" = "folded" ]; then
          echo "file=leap-deploy-folded.schema.json" >> $GITHUB_OUTPUT
        else
          echo "file=leap-deploy.schema.json" >> $GITHUB_OUTPUT
        fi

    - name: Validate configuration
      uses: dsanders11/json-schema-validate-action@v1.4.0
      with:
        schema: ${{ github.action_path }}/schemas/${{ inputs.version }}/${{ steps.schema.outputs.file }}
        files: ${{ inputs.file-path }}
        all-errors: true
