name: Leap Deploy Validate
description: |
  Validates leap-deploy.yaml or folded configuration against the predefined schema to ensure correctness.

inputs:
  file-path:
    description: Path to the configuration file
    required: true
  version:
    description: Schema version to validate against
    required: false
    default: "v0"
  schema-file:
    description: "Schema filename to validate against (e.g., leap-deploy.schema.json or leap-deploy-folded.schema.json)"
    required: false
    default: "leap-deploy.schema.json"

runs:
  using: composite
  steps:
    - name: Install JSON Schema CLI
      uses: sourcemeta/jsonschema@v14.0.4

    - name: Validate configuration
      shell: bash
      env:
        SCHEMA_DIR: ${{ github.action_path }}/schemas/${{ inputs.version }}
        SCHEMA_FILE: ${{ inputs.schema-file }}
        DATA_FILE: ${{ inputs.file-path }}
      run: |
        jsonschema validate \
          "${SCHEMA_DIR}/${SCHEMA_FILE}" \
          "${DATA_FILE}" \
          --resolve "${SCHEMA_DIR}" \
          --extension .schema.json \
          --verbose
