name: Leap Deploy Fold Config
description: |
  Folds leap-deploy.yaml configuration by merging workload configs for the specified environment and region.

inputs:
  file-path:
    description: Path to the leap-deploy.yaml configuration file
    required: true
  environment:
    description: Target environment (dev, staging, prod)
    required: true
  region:
    description: Target region (na, eu, etc.). Optional - if omitted, workload must not have region-specific configuration
    required: false
    default: ""

outputs:
  folded-config:
    description: The folded workload configuration in JSON format
    value: ${{ steps.fold.outputs.config }}
  folded-config-sources:
    value: ${{ steps.fold.outputs.config-sources }}
    description: The folded workload configuration formatted to show the source of each value

runs:
  using: composite
  steps:
    - name: Validate input configuration
      uses: workleap/wl-leap-deploy/.github/actions/validate@feature/tgh/feng-1587-4
      with:
        file-path: ${{ inputs.file-path }}
    
    - name: Fold configuration
      id: fold
      shell: bash
      env:
        ACTION_PATH: ${{ github.action_path }}
        FILE_PATH: ${{ inputs.file-path }}
        ENVIRONMENT: ${{ inputs.environment }}
        REGION: ${{ inputs.region }}
      run: |
        # Output 1: Run without show-sources for clean config and compact with jq -c
        CONFIG=$("$ACTION_PATH/fold-config.sh" \
          "$FILE_PATH" \
          "$ENVIRONMENT" \
          "$REGION" \
          "false" | jq -c '.')
        
        # Write folded config to temp file for validation
        FOLDED_TEMP=$(mktemp --suffix=.json)
        echo "$CONFIG" > "$FOLDED_TEMP"
        echo "folded-temp-file=$FOLDED_TEMP" >> $GITHUB_OUTPUT
        
        echo "config<<EOF" >> $GITHUB_OUTPUT
        echo "$CONFIG" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        
        # Output 2: Run with show-sources and pipe through show-sources.sh
        CONFIG_SOURCES=$("$ACTION_PATH/fold-config.sh" \
          "$FILE_PATH" \
          "$ENVIRONMENT" \
          "$REGION" \
          "true" | "$ACTION_PATH/show-sources.sh")
        echo "config-sources<<EOF" >> $GITHUB_OUTPUT
        echo "$CONFIG_SOURCES" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Validate folded configuration
      uses: workleap/wl-leap-deploy/.github/actions/validate@feature/tgh/feng-1587-4
      with:
        file-path: ${{ steps.fold.outputs.folded-temp-file }}
        schema-file: leap-deploy-folded.schema.json
